apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: documind
resources:
  - aws/deployment.yaml
  - aws/service.yaml
  - azure/deployment.yaml
  - azure/service.yaml
  - confluence/deployment.yaml
  - confluence/service.yaml
  - csv_ingest/deployment.yaml
  - csv_ingest/service.yaml
  - datadog/deployment.yaml
  - datadog/service.yaml
  - deploy/deployment.yaml
  - deploy/service.yaml
  - documents/deployment.yaml
  - documents/service.yaml
  - drills/deployment.yaml
  - drills/service.yaml
  - gcp/deployment.yaml
  - gcp/service.yaml
  - gdrive/deployment.yaml
  - gdrive/service.yaml
  - github/deployment.yaml
  - github/service.yaml
  - github_actions/deployment.yaml
  - github_actions/service.yaml
  - hr/deployment.yaml
  - hr/service.yaml
  - itsm/deployment.yaml
  - itsm/service.yaml
  - jira/deployment.yaml
  - jira/service.yaml
  - kubectl/deployment.yaml
  - kubectl/service.yaml
  - observe/deployment.yaml
  - observe/service.yaml
  - ollama/deployment.yaml
  - ollama/service.yaml
  - pagerduty/deployment.yaml
  - pagerduty/service.yaml
  - paperclip/deployment.yaml
  - paperclip/service.yaml
  - research/deployment.yaml
  - research/service.yaml
  - sentry/deployment.yaml
  - sentry/service.yaml
  - servicenow/deployment.yaml
  - servicenow/service.yaml
  - slack/deployment.yaml
  - slack/service.yaml
  - sonarqube/deployment.yaml
  - sonarqube/service.yaml
  - teams/deployment.yaml
  - teams/service.yaml
  - tests/deployment.yaml
  - tests/service.yaml
  - whatsapp/deployment.yaml
  - whatsapp/service.yaml
  - opa/all.yaml
