/**
 * Sidecar Advisor dashboard — read-only Server Component.
 *
 * Reads `.loop/dashboard.html` (rendered by `scripts/render_dashboard.py`)
 * from disk and embeds it. Operator runs the renderer on a cron
 * schedule + this page serves it.
 *
 * Why a Server Component reading static HTML, NOT a client-side
 * fetch + parse:
 *
 *  * The dashboard HTML is generated by Python (existing tooling).
 *    Re-implementing the data layer in Node would duplicate the
 *    render logic + risk drift between the static file and the UI.
 *  * Server Component reads the file at request time - no need for
 *    a separate API route. The page is render-only; no client JS.
 *  * Phase 1B-1 (this commit) is intentionally minimal. Phase 1B-2
 *    can add live data via better-sqlite3 reading advisor.db
 *    directly, with rating buttons + drill-down per event.
 *
 * Scope: this file is the §7 scope-extension granted entry for
 * `services/frontend/app/admin/sidecar/`. The rest of
 * `services/frontend/` remains gated per matrix row 18.
 */
import path from 'node:path';
import { promises as fs } from 'node:fs';

const DASHBOARD_PATH = path.resolve(
  process.cwd(),
  '..',
  '..',
  '.loop',
  'dashboard.html',
);

const FALLBACK_HTML = `
<div style="padding:24px;font-family:ui-monospace,monospace;color:#666">
  <h1>Sidecar Advisor</h1>
  <p>No dashboard rendered yet. Run from the repo root:</p>
  <pre style="background:#f6f7f9;padding:12px;border-radius:8px;
              border:1px solid #e0e0e0;font-size:13px">
python3 scripts/render_dashboard.py > .loop/dashboard.html</pre>
  <p>Then refresh this page. The renderer can be scheduled via cron
     for periodic refresh.</p>
</div>
`;

async function readDashboardHtml(): Promise<string> {
  try {
    return await fs.readFile(DASHBOARD_PATH, 'utf-8');
  } catch {
    return FALLBACK_HTML;
  }
}

export default async function SidecarDashboardPage() {
  const html = await readDashboardHtml();
  // Server-rendered, static; no XSS surface here because
  // render_dashboard.py html.escape()s every user-content cell.
  // The drill (drill_render_dashboard.py step 6) verifies this.
  return (
    <div className="sidecar-dashboard-frame">
      <div dangerouslySetInnerHTML={{ __html: html }} />
    </div>
  );
}

export const dynamic = 'force-dynamic';
