/**
 * Council telemetry — daily snapshot view (Server Component).
 *
 * Phase 5S surface for the snapshot file written by
 * `scripts/council_stats_snapshot.py` (Phase 5N). The script appends
 * one JSONL row per UTC date via cron (`5 0 * * *`, installed with
 * `scripts/install_snapshot_cron.sh --apply`); this page reads that
 * file at request time, dedups by date keeping the latest
 * `snapshot_taken_at` per date (matching Phase 5N's `read_snapshots`
 * contract), sorts newest-first, and renders the council outcome
 * counts as KPI cards + a table.
 *
 * Why a Server Component reading a static file (mirrors the pattern
 * established in `services/frontend/app/admin/sidecar/page.tsx`):
 *
 *  * The snapshot is generated by Python via cron; the data layer
 *    is owned by the Phase 5N tooling. Re-implementing it in Node
 *    risks drift between the JSONL row contract and the UI.
 *  * Reads happen at request time (`force-dynamic`); no client JS
 *    is shipped for the data layer.
 *  * Scope: `services/frontend/app/admin/sidecar/` is the granted
 *    extension surface; this file lives inside that scope.
 *
 * Robustness: missing or empty file yields a friendly bootstrap
 * message, never a thrown error. The page must always render so
 * operators get a clear next-step (run the cron installer).
 */
import path from 'node:path';
import { promises as fs } from 'node:fs';
import Link from 'next/link';

/**
 * One row of `.loop/council_stats_daily.jsonl`. Mirrors the schema
 * documented in `scripts/council_stats_snapshot.py` (Phase 5N).
 */
interface Snapshot {
  date: string;
  iso_week: string;
  total: number;
  fired: number;
  filtered: number;
  skipped: number;
  council_errors: number;
  fired_by_risk: Record<string, number>;
  filtered_by_reason: Record<string, number>;
  skipped_by_reason: Record<string, number>;
  snapshot_taken_at: string;
}

// Path resolution matches `services/frontend/app/admin/sidecar/page.tsx`:
// the frontend runs from `services/frontend/`, so `../../.loop/` lands
// on the repo-root `.loop/` directory. Two levels up, not three.
const SNAPSHOT_PATH = path.resolve(
  process.cwd(),
  '..',
  '..',
  '.loop',
  'council_stats_daily.jsonl',
);

/**
 * Parse the JSONL file. Returns `null` if the file is missing or empty
 * so the caller can render a bootstrap message rather than an error.
 *
 * Malformed individual lines are skipped (logged to server stderr
 * via `console.warn`); a single bad row should not blank the page.
 */
async function readSnapshotsFile(): Promise<Snapshot[] | null> {
  let raw: string;
  try {
    raw = await fs.readFile(SNAPSHOT_PATH, 'utf-8');
  } catch {
    return null;
  }
  const trimmed = raw.trim();
  if (!trimmed) return null;

  const rows: Snapshot[] = [];
  for (const line of trimmed.split('\n')) {
    const stripped = line.trim();
    if (!stripped) continue;
    try {
      rows.push(JSON.parse(stripped) as Snapshot);
    } catch (err) {
      // One bad line shouldn't blank the table — server-side log.
      console.warn('council_stats_daily.jsonl: skipping malformed line', err);
    }
  }
  return rows;
}

/**
 * Dedup by date, keeping the latest `snapshot_taken_at` per date.
 * Matches Phase 5N's `read_snapshots` contract (newest snapshot
 * wins) so the UI stays consistent with the Python tooling.
 */
function dedupByDate(parsed: Snapshot[]): Snapshot[] {
  const byDate = new Map<string, Snapshot>();
  for (const row of parsed) {
    const existing = byDate.get(row.date);
    if (!existing || row.snapshot_taken_at > existing.snapshot_taken_at) {
      byDate.set(row.date, row);
    }
  }
  // Newest date first — operators care about today / yesterday more
  // than the bottom of the history.
  return Array.from(byDate.values()).sort((a, b) =>
    a.date < b.date ? 1 : a.date > b.date ? -1 : 0,
  );
}

export default async function CouncilTelemetryPage() {
  const parsed = await readSnapshotsFile();
  const rows = parsed ? dedupByDate(parsed) : [];
  const totalSnapshots = parsed ? parsed.length : 0;
  const latestDate = rows.length > 0 ? rows[0].date : null;
  const totalEntries = rows.reduce((acc, r) => acc + r.total, 0);

  return (
    <>
      <div className="page-header">
        <div className="page-header-copy">
          <h1 className="section-title">Council Telemetry — Daily Snapshots</h1>
          <p className="page-subtitle">
            One row per UTC date, written by{' '}
            <code>scripts/council_stats_snapshot.py</code> via a{' '}
            <code>5 0 * * *</code> cron (install with{' '}
            <code>scripts/install_snapshot_cron.sh --apply</code>).
            Rows are deduped by date — the latest{' '}
            <code>snapshot_taken_at</code> wins, matching Phase 5N&rsquo;s{' '}
            <code>read_snapshots</code> contract.
          </p>
        </div>
      </div>

      {/* KPI strip — three cards summarising the snapshot file. */}
      <div className="metrics-strip">
        <div className="metric-card">
          <div className="metric-label">Snapshots collected</div>
          <div className="metric-value">{totalSnapshots}</div>
          <div className="field-help">
            Raw JSONL rows on disk (pre-dedup). Each cron run appends one.
          </div>
        </div>
        <div className="metric-card">
          <div className="metric-label">Latest date</div>
          <div className="metric-value">
            {latestDate ?? <span className="field-help">—</span>}
          </div>
          <div className="field-help">
            Newest UTC date with a snapshot row.
          </div>
        </div>
        <div className="metric-card">
          <div className="metric-label">Total entries observed</div>
          <div className="metric-value">{totalEntries}</div>
          <div className="field-help">
            Sum of <code>total</code> across all deduped daily rows.
          </div>
        </div>
      </div>

      {/* Empty / not-yet-bootstrapped state. */}
      {parsed === null || rows.length === 0 ? (
        <div className="card">
          <div className="list-empty">
            No snapshots yet — run{' '}
            <code>scripts/install_snapshot_cron.sh --apply</code> to start
            collecting. The cron writes one row per UTC date to{' '}
            <code>.loop/council_stats_daily.jsonl</code>; this page will
            populate on the next refresh after the first run.
          </div>
        </div>
      ) : (
        <div className="card">
          <div className="card-header" style={{ marginBottom: 12 }}>
            <strong>Daily counts</strong>
            <div className="field-help">
              Newest first. Rows where <code>total = 0</code> are
              dimmed because they represent a quiet day with no
              council activity recorded.
            </div>
          </div>
          <div className="table-wrap">
            <table className="table">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Total</th>
                  <th>Fired</th>
                  <th>Filtered</th>
                  <th>Skipped</th>
                  <th>Errors</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((r) => {
                  const muted = r.total === 0;
                  // Inline `style` is allowed only for the muted-row
                  // color rule per spec; everything else flows from
                  // globals.css + design tokens in variables.css.
                  const mutedStyle = muted
                    ? { color: 'var(--text-muted)' }
                    : undefined;
                  return (
                    <tr key={r.date}>
                      <td style={mutedStyle}>
                        <code>{r.date}</code>
                      </td>
                      <td style={mutedStyle}>{r.total}</td>
                      <td style={mutedStyle}>{r.fired}</td>
                      <td style={mutedStyle}>{r.filtered}</td>
                      <td style={mutedStyle}>{r.skipped}</td>
                      <td style={mutedStyle}>{r.council_errors}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* See also — links back to the architecture deep dive + the
          live dashboard. Markdown-style "see also" rendered as real
          anchors so the operator can click. */}
      <div className="card">
        <div className="card-header" style={{ marginBottom: 12 }}>
          <strong>See also</strong>
        </div>
        <ul>
          <li>
            <Link href="/admin/sidecar/deep">Deep dive</Link> — for the
            architecture.
          </li>
          <li>
            <Link href="/admin/sidecar">Live dashboard</Link> — for real-time
            activity.
          </li>
        </ul>
      </div>
    </>
  );
}

// Read at request time so a fresh snapshot lands in the UI without
// requiring a redeploy or cache bust.
export const dynamic = 'force-dynamic';
