apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: documind-sensitive-file-access
spec:
  kprobes:
    - call: "security_file_open"
      syscall: false
      args:
        - index: 0
          type: "file"
      selectors:
        - matchArgs:
            - index: 0
              operator: "Prefix"
              values:
                - "/etc/kubernetes/"
                - "/var/run/secrets/kubernetes.io/"
                - "/mnt/deepa/rag/.env"
                - "/mnt/deepa/rag/data/secrets/"
          matchActions:
            - action: Post
---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: documind-privilege-and-shell-exec
spec:
  kprobes:
    - call: "sys_execve"
      syscall: true
      args:
        - index: 0
          type: "string"
      selectors:
        - matchArgs:
            - index: 0
              operator: "Equal"
              values:
                - "/bin/sh"
                - "/bin/bash"
                - "/usr/bin/sudo"
                - "/usr/bin/nsenter"
                - "/usr/bin/unshare"
                - "/usr/bin/chmod"
                - "/usr/bin/chown"
          matchActions:
            - action: Post
---
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: documind-network-egress-observe
spec:
  kprobes:
    - call: "tcp_connect"
      syscall: false
      args:
        - index: 0
          type: "sock"
      selectors:
        - matchActions:
            - action: Post
