apiVersion: v1
kind: Service
metadata:
  name: mcp-datadog
  namespace: documind
  labels:
    app: mcp-datadog
    documind.tool/namespace: datadog
spec:
  selector:
    app: mcp-datadog
  ports:
    - port: 8123
      targetPort: 8123
      name: http
      protocol: TCP
