tracee:
  output:
    json: true
    option:
      parseArguments: true
      parseArgumentsFDs: true
  rules:
    enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  securityContext:
    privileged: true
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
    - operator: Exists
