#!/usr/bin/env bash
set -euo pipefail

# Start every repo-local MCP server on deterministic localhost ports.
#
# The script writes:
#   .loop/mcp-local.env   source-able DOCUMIND_MCP_<NS>_URL exports
#   .loop/mcp-local.pids  process table for stop/restart
#
# Usage:
#   bash scripts/start_local_mcp_fleet.sh start
#   source .loop/mcp-local.env
#   .venv/bin/python scripts/mcp_fleet_health.py --full
#   bash scripts/start_local_mcp_fleet.sh stop

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PY="${PYTHON_BIN:-$ROOT/.venv/bin/python}"
LOOP="$ROOT/.loop"
ENV_FILE="$LOOP/mcp-local.env"
PID_FILE="$LOOP/mcp-local.pids"
LOG_DIR="$LOOP/mcp-logs"

mkdir -p "$LOOP" "$LOG_DIR"

if [[ ! -x "$PY" ]]; then
  echo "error: project Python not found at $PY" >&2
  exit 2
fi

servers=(
  "hr:8090:MCP_HR_PORT"
  "itsm:8091:MCP_ITSM_PORT"
  "drills:8092:MCP_DRILLS_PORT"
  "documents:8093:MCP_DOCUMENTS_PORT"
  "research:8094:MCP_RESEARCH_PORT"
  "tests:8095:MCP_TESTS_PORT"
  "deploy:8096:MCP_DEPLOY_PORT"
  "observe:8097:MCP_OBSERVE_PORT"
  "ollama:8098:MCP_OLLAMA_PORT"
  "paperclip:8099:MCP_PAPERCLIP_PORT"
  "csv_ingest:8100:MCP_CSV_INGEST_PORT"
  "aws:8101:MCP_AWS_PORT"
  "azure:8102:MCP_AZURE_PORT"
  "confluence:8103:MCP_CONFLUENCE_PORT"
  "datadog:8104:MCP_DATADOG_PORT"
  "gcp:8105:MCP_GCP_PORT"
  "gdrive:8106:MCP_GDRIVE_PORT"
  "github:8107:MCP_GITHUB_PORT"
  "github_actions:8108:MCP_GITHUB_ACTIONS_PORT"
  "jira:8109:MCP_JIRA_PORT"
  "kubectl:8110:MCP_KUBECTL_PORT"
  "pagerduty:8111:MCP_PAGERDUTY_PORT"
  "sentry:8112:MCP_SENTRY_PORT"
  "servicenow:8113:MCP_SERVICENOW_PORT"
  "slack:8114:MCP_SLACK_PORT"
  "sonarqube:8115:MCP_SONARQUBE_PORT"
  "teams:8116:MCP_TEAMS_PORT"
  "whatsapp:8117:MCP_WHATSAPP_PORT"
)

to_env_name() {
  local ns="$1"
  echo "DOCUMIND_MCP_${ns^^}_URL"
}

stop_fleet() {
  if [[ ! -f "$PID_FILE" ]]; then
    echo "no pid file at $PID_FILE"
    return 0
  fi
  while read -r ns pid _port; do
    [[ -z "${pid:-}" ]] && continue
    if kill -0 "$pid" 2>/dev/null; then
      kill "$pid" 2>/dev/null || true
      echo "stopped $ns pid=$pid"
    fi
  done < "$PID_FILE"
  rm -f "$PID_FILE"
}

write_env_file() {
  {
    echo "# Generated by scripts/start_local_mcp_fleet.sh"
    echo "# shellcheck shell=bash"
    for row in "${servers[@]}"; do
      IFS=: read -r ns port _port_env <<< "$row"
      echo "export $(to_env_name "$ns")=http://127.0.0.1:$port"
    done
  } > "$ENV_FILE"
}

start_one() {
  local ns="$1" port="$2" port_env="$3"
  local module="mcp.server_${ns}"
  local log="$LOG_DIR/$ns.log"

  if "$PY" - "$port" <<'PY' >/dev/null 2>&1
import socket
import sys

port = int(sys.argv[1])
with socket.socket() as s:
    s.settimeout(0.2)
    sys.exit(0 if s.connect_ex(("127.0.0.1", port)) == 0 else 1)
PY
  then
    echo "$ns already listening on $port"
    return 0
  fi

  (
    cd "$ROOT"
    export "$port_env=$port"
    exec nohup "$PY" -m uvicorn "${module}:app" --host 127.0.0.1 --port "$port" > "$log" 2>&1
  ) &
  echo "$ns $! $port" >> "$PID_FILE"
  echo "started $ns pid=$! port=$port log=$log"
}

cmd="${1:-start}"
case "$cmd" in
  -h|--help)
    cat <<EOF
Usage: $0 {start|serve|stop|restart|env|--help}

Start every repo-local MCP server on deterministic localhost ports.
Writes .loop/mcp-local.env (sourceable URL exports) and
.loop/mcp-local.pids (pid table) for stop/restart.

  start    Start the fleet (default if no arg given)
  serve    Start + block (Ctrl+C to stop)
  stop     Stop all started fleet members
  restart  stop + start
  env      Print sourceable env file
  -h, --help  Print this help
EOF
    exit 0 ;;
  start)
    stop_fleet
    : > "$PID_FILE"
    write_env_file
    for row in "${servers[@]}"; do
      IFS=: read -r ns port port_env <<< "$row"
      start_one "$ns" "$port" "$port_env"
    done
    echo
    echo "env written: $ENV_FILE"
    echo "next: source $ENV_FILE && $PY scripts/mcp_fleet_health.py --full"
    ;;
  serve)
    "$0" start
    trap '"$0" stop' INT TERM EXIT
    echo "serving local MCP fleet; press Ctrl+C to stop"
    while true; do
      sleep 3600
    done
    ;;
  stop)
    stop_fleet
    ;;
  restart)
    "$0" stop
    "$0" start
    ;;
  env)
    write_env_file
    cat "$ENV_FILE"
    ;;
  *)
    echo "usage: $0 {start|serve|stop|restart|env}" >&2
    exit 2
    ;;
esac
